# Introduction to pandas
- Pandas is a Python module designed to handle tabular data.
- Tabular data - data that has a shape like a table, with rows and columns.
- By convention, we use the short alias `pd` for pandas

In [2]:
# importing the package(s) we want to use
import pandas as pd

## Create data
There are two core objects in pandas: the [**DataFrame**](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.html) and [**Series**](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.Series.html). In this exercise, we will create some sample data and also read from an existing file.

### **Series**  
A series is similar to a list and can be created by nothing more than a list. It has 2 additional attributes other than the list content; index and datatype


It is different than a list and has two additional attributes:
1.   An explicit index
2.   Type dtype (data type).

A dtype can be integer, float, and object. int64 - in Python which stands for 64 bit integer. The 64 refers to the memory allocated to store data in each cell which effectively relates to how many digits it can store in each “cell”

In [4]:
# Converting a list into a pandas series
mylist = ['a','b','c','d']
my_series = pd.Series(mylist)
# print(my_series.dtype)
my_series

0    a
1    b
2    c
3    d
dtype: object

We can also create a pandas Series with a *list of strings*

In [ ]:
sList = ['ABC','DEF','GHI']

# Creating a series
s = pd.Series(sList)
print(s.dtype)

object

Noticed that the dtype is `object`, not `str` as expected.   
This is because panadas uses object by default for strings. You can explicitly set the dtype to string by using the dtype argument.

In [ ]:
# using the dtype attribute to convert the obj to string
pd.Series(sList, dtype="string")

0    ABC
1    DEF
2    GHI
dtype: string

A Series is, in essence, a single column of a DataFrame. So you can assign column values to the Series, using an index parameter via `index`. However, a Series does not have a column name, it only has one overall name, assigned as `name`.

In [ ]:
revenue = [30, 38, 58]
years = ['2018 Sales', '2019 Sales', '2020 Sales']

# using the name and index attribute
pd.Series(revenue, index=years, name="Product A")

2018 Sales    30
2019 Sales    38
2020 Sales    58
Name: Product A, dtype: int64

### **DataFrame**   
We can think of a Series as a list and a DataFrame as a table,. By convention, we use a generic name `df` for DataFrame objects. A DataFrame is made of multiple Series combined together.
   
We are using the `pd.DataFrame()` to generate these DataFrame objects. To convert a dictionary into a DataFrame object, pandas will use the **keys** into the column names and the **value** will be the data entry for the columns.

In [ ]:
my_dict = {
  'cars': ["BMW", "Volvo", "Ford"],
  'passings': [3, 7, 2]
}

# Convert a dictionary into data frame
my_df = pd.DataFrame(mydataset)

print(my_df)

    cars  passings
0    BMW         3
1  Volvo         7
2   Ford         2

Additionally, you can use multiple lists to construct a DataFrame object. The syntax for declaring a new one is a dictionary whose **keys** are the **column names** (Names and Scores in this example), and whose **values** are a **list of entries**. This is the standard way of constructing a new DataFrame, and the one you are most likely to encounter.

In [ ]:
# create a df with list and providing a custom index by using a dictionary adjacent structure

list1 = ['a','b','c', 'd']
list2 = [1,3,4,7]

df = pd.DataFrame({"Names": list1, "Scores": list2})
df

  Names  Scores
0     a       1
1     b       3
2     c       4
3     d       7

The dictionary-list constructor assigns values to the column labels, but just uses an ascending count from 0 (0, 1, 2, 3, ...) for the **row labels**.

A list of row labels known as an **Index** can be used in a DataFrame. We can assign values to it by using an index parameter in our constructor.

In [ ]:
# Specify a custom index using the index parameter

productList = ['Product A', 'Product B', 'Product C', 'Product D']
pd.DataFrame({"Names": list1, "Scores": list2}, index=productList)

          Names  Scores
Product A     a       1
Product B     b       3
Product C     c       4
Product D     d       7

### Index-based selection
The Series and the DataFrame are intimately related. It's helpful to think of a DataFrame as actually being just a bunch of Series "glued together". We can use indexing operators, `iloc` and `loc`, to select for data.
  
Pandas has its own indexing operators, `iloc` and `loc`.
- `.iloc[ ]`: index-based selection that selects data based on its numerical position in the data
- `.loc[ ]`: primarily label based

&nbsp;  
**Indexing in pandas**  
- [start:stop:skip] #stop is exclusive [1:3] --> index 1 & 2  
- [1::2, :] #from the 2nd row all the way to the end every other row, and all the columns  
- [:, :3] #all rows, from the beginning to the 3rd column (0, 1, 2)

In [11]:
netflix_dataset = {
  'Title': ["Popeye", "Shot Caller", "Strong Girl Bong-soon", "Charlotte's Web", "End of Watch"],
  'Director': ["Robert Altman", "Ric Roman Waugh", "", "Charles A. Nichols, Iwao Takamoto", "David Ayer"],
  'Release_Date': [1980, 2017, 2017, 1973, 2012],
  'Duration(min)': ["114 min", "121 min", "1 season", "94 min", "109 min"],
}


# Convert a dictionary into data frame
df = pd.DataFrame(netflix_dataset, index = ["show1", "show2", "show3", "show4", "show5"])
df

,Title,Director,Release_Date,Duration(min)
show1,Popeye,Robert Altman,1980,114 min
show2,Shot Caller,Ric Roman Waugh,2017,121 min
show3,Strong Girl Bong-soon,,2017,1 season
show4,Charlotte's Web,"Charles A. Nichols, Iwao Takamoto",1973,94 min
show5,End of Watch,David Ayer,2012,109 min

In [14]:
## Select the first row and 2 column by numeric-based
# df.iloc[0, 1]

## Select the first row and 2 column by label-based
# df.loc["show1", "Director"]

'Robert Altman'

### Your turn now!

**Question CL11.1**  
How do you get row 2 through 4 using numeric-based selection?

In [ ]:
### Your code here

                        Title      Gross
3  E.T. the Extra-Terrestrial  435110554
4                     Titanic  659363944
5        The Ten Commandments   65500000

**Question CL11.2**  
How do you get `Release_Date` column?  through 4 using numeric-based selection?

In [ ]:
### Your code

**Question CL11.3**  
How do you get row 2-3 and column 4 using either index-based selection?

In [ ]:
### Your code

#### To select a single value we can use `iat`.

In [ ]:
movies.iat[0, 0]

'Gone with the Wind'

**Question CL11.4**  
Use iat to select for the show Title `Charlotte's Web`

**Question CL11.4**  
How do you get row 2-3 and column 4 using either index-based selection?

### Using date_range()

Purpose: Generates a fixed-frequency Datetime Index, useful for creating time series data.

Usage: Widely used in time series data analysis for generating date sequences as index for DataFrame or for iteration.

Syntax Example: pd.date_range(start='2024-01-01', end='2024-12-31', freq='D')

In [ ]:
dates = pd.date_range("20130101", periods=6)

In [ ]:
s = pd.Series([1, 2, 3, 4, 5, 6], index=pd.date_range("20130102", periods=6))

**Setting values, Assigning new columns**

In [ ]:
df = pd.DataFrame(np.random.randn(6, 4), index=dates, columns=list("ABCD"))
# df["E"] = ["one", "one", "two", "three", "four", "three"]
# df = df[df["E"].isin(["two", "four"])]

In [ ]:
# df[df > 0] = -df

### Working with missing values
Different methods to work with missing values include dropna, isna, and fillna

#### **dropna():**

Purpose: Removes missing values from a DataFrame or Series.

Usage: df.dropna(axis=0, how='any')  


#### **isna():**

Purpose: Identifies missing values, returning a boolean mask indicating their location.

Usage: df.isna()

#### **fillna():**

Purpose: Fills missing values in a DataFrame or Series with a specified value or method.

Usage: df.fillna(value=0, method=None)

In [21]:
NA_data = {"A":["2013-01-01",	-1.011827,	-2.038640,	-0.059264,	0.499834],
           "B":["2013-01-02",	1.342215,	2.252956,	-0.104036,	0.303247],
           "C":["=2013-01-03",	-0.743262,	1.780086,	-2.131797,	-0.176982],
           "D":["2013-01-04",	-0.333518,	0.389989,	0.185417,	0.096673],
           "E":["2013-01-05",	-0.512518,	-1.952316,	-0.006880,	1.410644],
           "F":["2013-01-06",	-0.795746,	0.416914,	-0.014726,	-0.116601]
}
NA_data
df2 = pd.DataFrame(NA_data)
df2

            A           B            C           D           E           F
0  2013-01-01  2013-01-02  =2013-01-03  2013-01-04  2013-01-05  2013-01-06
1   -1.011827    1.342215    -0.743262   -0.333518   -0.512518   -0.795746
2    -2.03864    2.252956     1.780086    0.389989   -1.952316         NaN
3   -0.059264   -0.104036    -2.131797    0.185417    -0.00688         NaN
4    0.499834    0.303247    -0.176982    0.096673    1.410644         NaN

In [26]:
import numpy as np
df["F"] = [1, 2, np.nan, np.nan, np.nan]
df.isna()
# pd.isna(df)

       Title  Director  Release_Date  Duration(min)      F
show1  False     False         False          False  False
show2  False     False         False          False  False
show3  False     False         False          False   True
show4  False     False         False          False   True
show5  False     False         False          False   True

In [27]:
df

,Title,Director,Release_Date,Duration(min),F
show1,Popeye,Robert Altman,1980,114 min,1.0
show2,Shot Caller,Ric Roman Waugh,2017,121 min,2.0
show3,Strong Girl Bong-soon,,2017,1 season,NaN
show4,Charlotte's Web,"Charles A. Nichols, Iwao Takamoto",1973,94 min,NaN
show5,End of Watch,David Ayer,2012,109 min,NaN

In [ ]:
# df.fillna(value=5)