# Using Pandas to explore your data file
- In Colab notebook 11, we learned that Pandas is designed to handle tabular data.
- In this notebook we will continue to use Pandas to explore data further using a real dataset.

In [ ]:
### importing the package(s) we want to use
import pandas as pd

### Reading data files ###
Being able to create a DataFrame or Series by hand is handy. But, most of the time, we won't actually be creating our own data by hand. Instead, we'll be working with data that already exists.

We'll use the `pd.read_csv()` function to read the data into a DataFrame.  

This method assumes your tabular datafile is a csv file. However, if your tabular datafile has a different delimiter such as a tab('\t\) or semicolon(';'), you can set the delimiter using `sep='\t'`.

In [ ]:
csvFile = 'https://raw.githubusercontent.com/csbfx/advpy122-data/master/top_movies_2020.csv'

### Create a df that reads in csvFile

                                Title      Gross  Gross (Adjusted)  Year
0                  Gone with the Wind  200852579        1895421694  1939
1  Star Wars: Episode IV - A New Hope  460998507        1668979715  1977
2                  The Sound of Music  159287539        1335086324  1965
3          E.T. the Extra-Terrestrial  435110554        1329174791  1982
4                             Titanic  659363944        1270101626  1997

It is useful when you work with a new datafile for you to check the DataFrame using `head()` or `tail()`.
Useful things to notice is the correct delimiter was used, the presence of a header, the index, are there missing values or incorrectly formatted data?

In [ ]:
### Checking that the data was imported correctly using head() or tail()

                                Title      Gross  Gross (Adjusted)
0                  Gone with the Wind  200852579        1895421694
1  Star Wars: Episode IV - A New Hope  460998507        1668979715
2                  The Sound of Music  159287539        1335086324
3          E.T. the Extra-Terrestrial  435110554        1329174791
4                             Titanic  659363944        1270101626

### `.info()` method to get information about columns
We can even get more information about the columns by calling the `info()` method.  
This will tell us a bunch more information. From top to bottom we can see:
- what class the object is (a DataFrame)
- what the index looks like (a range from Gone with the Wind to Liar Liar)
- how many data columns we have
- for each column, how many values and their dtype
- a summary of how many columns have each dtype
- how much memory the object is taking up

In [ ]:
# movies.info()

### Working with columns in a dataframe
You can work with a single or multiple columns at a time to sort, count elements, find unique elements, or subsetting DataFrame to column.
   
For example, you can sort elements in a column using the `sort_values()` method with parameter `ascending` to sort arranged data from smallest to largest or vice versa.

In [ ]:
### You can sort by one or more columns
## Sort 'Title' from Z-A

## Sort 'Title' and 'Year' from Z-A, and 0-9

                  Title      Gross  Gross (Adjusted)  Year
198            Zootopia  341268248         371109157  2016
138  Young Frankenstein   86273333         427715201  1974
134        Wonder Woman  412563408         432102235  2017
80      West Side Story   44055492         524839936  1961
90              Twister  241721524         512427497  1996

Any time we see a question involving the words ”how many ... for each ...” "how many ... for each ..." the answer is `value_counts()`.

In [ ]:
# movies.Title.value_counts()

We can customize the **column header** names by assigning values to the columns attribute. This method requires that you define all the column names.

In [ ]:
### Change column names via .column
 = ['Movie','Gross','Gross_adj','Year']

To subset the df, pass in the list of columns you want to keep

In [ ]:
### Subset_movies with columns 'Movie' and 'Year'
subset_movies =

To get statistic summary about the contents of the different columns, we can try the `describe` method:
You can run describe() on a specific column (which is a Series rather than a DataFrame).  
- movies.Gross_adj.describe()   
- movies["Gross_adj"].describe()
- movies.drop(columns=['Year']).describe()

In [ ]:
## Get the statistic on a Series
# movies.Gross.describe()

## Get the statistic on multiple columns in dataframe

## Use drop() to not include a column when looking for statistic

It's hard to read the numbers in scientific notation. We can change the number format just to make it more standard(with commas and 2 decimal values).

In [ ]:
### Change the display format for float
## Use commas to separate thousands and use 2 decimal points
pd.options.display.float_format = "{:,.2f}".format

movies.drop(columns=['Year']).describe()

               Gross        Gross_adj
count         200.00           200.00
mean  256,492,048.62   560,869,366.30
std   170,567,531.47   227,797,683.45
min     9,183,673.00   370,330,510.00
25%   116,926,360.25   414,518,727.25
50%   234,196,310.00   500,451,231.50
75%   363,303,312.50   616,672,963.50
max   936,662,225.00 1,895,421,694.00

You can drop a column in a dataframe using the `drop()` method. Use the `inplace` parameter to result in the operation occuring inplace.

In [ ]:
## Drop the column 'Year' inplace.
movies.drop(<column, inplace>)

### Question 12.1: Find the mean value
How would you get the mean value of 'Gross' in the movies dataframe?   
*Hint*: Use `mean()` on a Series or specific column

In [ ]:
### Your code

### Random library
Using the numpy library, we can create arrays. Use `np.random.rand(row,col)` to create an array of the given shape and populate array with random values from a uniform distribution over [0, 1)

In [ ]:
import numpy as np
import pandas as pd
import random
df = pd.DataFrame(np.random.rand(4, 4), columns=list("ABCD"))
df

          A         B         C         D
0  0.045017  0.331361  0.136455  0.623842
1  0.328472  0.443630  0.083349  0.762707
2  0.213277  0.864154  0.053173  0.266171
3  0.559147  0.345567  0.997872  0.009037

# Selection and indexing
### **loc** and **at**

In the world of data manipulation with pandas, efficiently accessing and modifying data is fundamental. Pandas provides several methods to retrieve and modify data in DataFrame and Series objects, with .loc[], iloc[], and .at[] being among the most powerful and commonly used for label-based access.

**.loc[] Accessor:**

- Purpose: Access a group of rows and columns by labels or a boolean array.
- Usage: Ideal for selecting subsets of rows and columns.
- Syntax Example: df.loc[row_label, column_label]
- Key Points: Can be used to select single rows/columns, slices, or multiple rows/columns by label. Supports boolean indexing (df.loc[df['a'] > 100]).

**.at[] Accessor:**
- Purpose: Access a single value for a row/column label pair.
- Usage: Optimized for fast access to a single element. More efficient than .loc[] for this purpose.
- Syntax Example: df.at[row_label, column_label]
- Key Points: Only useful for accessing a single value at a time. Throws an error if the specified labels do not exist in the DataFrame.

In [ ]:
movies.loc[0:2, ["Title",	"Gross"]]

                                Title      Gross
0                  Gone with the Wind  200852579
1  Star Wars: Episode IV - A New Hope  460998507
2                  The Sound of Music  159287539

In [ ]:
movies.at[0, "Title"]

'Gone with the Wind'

### iloc and iat

**.iloc[] Accessor:**
- Purpose: Access a group of rows and columns by integer positions.
- Usage: Ideal for selecting subsets of rows and columns based on their integer index, regardless of the DataFrame's index labels.
- Syntax Example: df.iloc[row_index, column_index]
- Key Points: Enables selection of single rows/columns, slices, or multiple rows/columns by integer position. Does not support boolean indexing directly but can be used with boolean arrays indirectly through positions.


**.iat[] Accessor:**
- Purpose: Access a single value by its integer position.
- Usage: Optimized for fast access to a single element, similar to .at[] but uses integer positions instead of labels.
- Syntax Example: df.iat[row_index, column_index]
- Key Points: Designed exclusively for accessing a single value quickly. It is more efficient than .iloc[] for this specific purpose. Throws an error if the specified integer positions are out of bounds.

#### Question 12.2: Access rows and columns
How would you get rows 3 through 7 and columns 0 and 1?

In [ ]:
### Your code

**Setting values, Assigning new columns**

In [ ]:
df = pd.DataFrame(np.random.randn(6, 4), index=dates, columns=list("ABCD"))
# df["E"] = ["one", "one", "two", "three", "four", "three"]
# df = df[df["E"].isin(["two", "four"])]

In [ ]:
# df[df > 0] = -df

### Filtering dataframe

In [ ]:
fruitdict = {'apples':[10,4,8], 'oranges':[14,2,7], 'bananas': [19,45,1], 'color':['yellow','green','red']}
fruitdf = pd.DataFrame(fruitdict, index=['orchard1', 'orchard2', 'orchard3'])
fruitdf

          apples  oranges  bananas   color
orchard1      10       14       19   green
orchard2       4        2       45  yellow
orchard3       8        7        1     red

In [ ]:
### Filter for rows where target column has a particular value.
## Select row based on condition where 'banana' is equal to 45
fruitdf

          apples  oranges  bananas   color
orchard2       4        2       45  yellow

In [ ]:
### Filter for rows that are found in a list using isin()
flist = ['red','yellow']

          apples  oranges  bananas   color
orchard2       4        2       45  yellow
orchard3       8        7        1     red

In [ ]:
### Filter using multiple conditions
fruitdf[(fruitdf['apples']>0) & (fruitdf['apples']<=5)]

          apples  oranges  bananas   color
orchard2       4        2       45  yellow

### Question 12.3: Filter based on condition
Use the movies dataset from above and filter out movies that had a 'Gross (Adjusted)' value greater than 1350000000.

In [ ]:
### Your code

### Question 12.4: Filter based on multiple conditions
Use the movies dataset from above and filter out movies that had a 'Gross (Adjusted)' value greater than 1000000000 that were release between the years 1970 to 1990.

In [ ]:
### Your code